### ISSUE TITLE
Grammarly integration?

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#105]
https://developer.grammarly.com/docs/

**Comment by zefhemel** [comment]
@hanzei tells me this just works if you have grammarly installed without explicit support 🤷🏻

**Comment by zefhemel** [comment]
Ok, this just seems to work out of the box due to the magic of... this being a web app and Grammarly having a chrome extension. Closing.

**Comment by AndrewDiMola** [comment]
_Ok, this just seems to work out of the box due to the magic of... this being a web app and Grammarly having a chrome extension. Closing._

@zefhemel - We're working on our rules for precedence across Grammarly products, but, yes, if someone has the extension enabled (at present), it will override a local SDK integration (for the provided plugin). That said, I can see silverbullet gaining some amount of utility from an opt-in Grammarly integration. Disclaimer: I manage the above documentation site and am looking through mentions across GitHub.
