### ISSUE TITLE
[Collab] Persistence when all clients leave the room

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet#157]
What happens if I close my SB? I would assume no changes are reflected back to me. So assuming your public y.js server is only a signalling server, changes would be lost if all collaborators leave the room?

Possible solution:
- indicate the number of users that are working on the note currently
- also indicate which users are working on the note AND persisting it at the same time
- indicate very visibly when all persisting users have left the room and warn on closing the window

I'm aware this will require some logic through signalling, but it should be straight forward to implement, right? Assuming the quesiton of persistence is easily answered via existing APIs. If so, I might try to contribute if that's something you're open to?

**Comment by zefhemel** [comment]
As it works today (and this is also the case for `collab.silverbullet.md`) the server has persistent storage for all pages shared using it for exactly the reason you point out, this way you can always get the updates for changes that happened when you weren't connected. Right now this data is never purged, nor can you explicitly delete any data from the server this way. However, this is what the off-the-shelf y.js server offers.

It's far from ideal and likely will need iteration. I see the current implementation as a proof of concept. At some point I think we need to fork the server (and maybe rework it to run on Deno) to be able to add more options.

If you're interested in owning this I'd be very happy. This is an interesting area, but I got 100 more of those to focus on. 

Since your assumption was that this only works when multiple people have a page open at the same time (which isn't the case), a few thoughts: I think this ability to do "async" collaboration (so also editing when the other person isn't there) is quite key. Also since you leave and join collab session as you switch pages, it would otherwise be very easy to miss signals without it.

A whole other area to explore is, once again: authentication and security. Right now, if you know a "room ID" you're in. No permissions, it's a free for all. Likely we'd like to have at least password authentication for a server, and perhaps even "read only" participants at some point.

All reasons to want to fork the server part, to get more control over what's supported.

**Comment by yorrd** [comment]
@zefhemel gotcha. Thanks for the explanation. I wasn't aware the default y.js-server worked that way... 

I'm going to pull our team into this discussion internally and see if we can allocate some ressources towards improving the collab situation. 

About authentication: you're having a discussion in https://github.com/silverbulletmd/silverbullet/issues/16 about whether to outsource authentication. I guess these discussions should be aligned? Wondering about your opinion here. Do you see a good practice happening any time soon? I'm aware the auth situations are quite different, one being possible through auth wrappers and the other needing integration into silverbullet plugs. If the other discussion ends up moving towards built-in authentication though, that might be something to integrate into the collab solution as well though, e.g. documents being owned by someone who then allows access to other user accounts. 
This is different from the room authentication method. Depending on the use case, both might be justifiable. Sharing meeting notes would probably be on a room-basis, whereas a shared documentation setup might benefit from file owners who can restrict access. Haven't thought this through though, appreciate your input here. 

Btw, appreciate you pulling together those repos into one. Feels more efficient for the moment.

**Comment by zefhemel** [comment]
> About authentication: you're having a discussion in https://github.com/silverbulletmd/silverbullet/issues/16 about whether to outsource authentication. I guess these discussions should be aligned? Wondering about your opinion here. Do you see a good practice happening any time soon?

I think there's two types of authentication here: of SilverBullet itself (which is what #16 about) and authentication with "third party" services. Personally, I'm thinking of authentication with a collaboration server as a third party. Right now we have no great way to do this other than the convention of keeping keys or tokens in a `SECRETS` page. Likely at some point we'll want to allow oAuth type flows to make this more user friendly and safe. 

Either way, I think authenticating with SB itself is separate from collab authentication and I see no strong argument right now to want to merge them. So we're free to figure out how authentication and authorization would work for collaboration. Could be a shared token that gives read-write access, could be a user-specific token where the collab side can manage who gets what type of access, for instance.

**Comment by yorrd** [comment]
gotcha. Thanks for insight into your judgement here. Seems conherent to me. Let me get back to this when I've gotten feedback from our team on the most likely user stories here. 

We might first put emphasis on a potential [backstage](https://backstage.io/) integration. That's our first means of "collaborating". On top of that, I would like to be able to edit those md files together in our meetings. Let me play around with that thought for a while...
