### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by vuau** [silverbulletmd/silverbullet#171]
Does SilverBullet work offline? I tried both siverbullet.md and the local server but neither of them works when I turn off the network.

**Comment by vuau** [comment]
I meant fully offline/ disconnected from server. Hope #59 will gain enough interest to be implemented in the near future.

**Comment by drawtheliner** [comment]
I'm not sure if what I want is related to this (it seems to be, but the link to discussion #59 is broken), but I thought I'd ask here first to avoid creating a duplicate issue.

I don't have enough technical skills to set up a server/docker.

I'd like to be able to just use Silverbullet locally on my personal laptop and phone, syncing between them directly when needed only via my local network (ie. no need for a server). I don't want my data kept elsewhere (in some cloud service) either, nor ever leaving my local network.

From what I understood, this isn't currently possible. Are there plans for something like this in the near or distant future?

**Comment by zefhemel** [comment]
Not right now. The focus right now is to let people self host this on their own server. What you're asking for would require a hosted version, which is maybe something to pursue in time but it's not a focus now.

**Comment by drawtheliner** [comment]
> What you're asking for would require a hosted version

Dziękuję for replying! Sorry for my ignorance, but what do you mean by "hosted version"?

I know the word "hosted" in the context of website hosting - a server elsewhere where I'd keep my website, files etc.

What I'd like is the opposite of that. My files would live exclusively in my devices, and synced between them only via my local network (ie. never reaching the internet).

The only apps I've personally used which do this kind of thing (sync between devices within local network only) are Anytype and Syncthing.

**Comment by zefhemel** [comment]
With hosted I mean that there’s a website where you can just sign up to create an account and your content lives there. But from your description this is also not what you’re looking for, what you’re looking for is a peer-to-peer sync solution. That’s quite far from how SilverBullet is designed right now. What you could do is run SilverBullet locally on your laptop, and then on another laptop and use syncthing to sync data between them, that would work. Doing this with a mobile device will be problematic, because you cannot just run a web server there and syncthing. 

So the the short answer for what you’re trying to do I don’t think SilverBullet is a good option at this time. 

On a side note, I don’t know how important it is for you that your data never leaves your local network, but I think this is not guaranteed with syncthing and anytype either, both likely likely will use Internet connected machines to do syncs in certain scenarios. I’m sure this is all encrypted, so it should be safe, though.

**Comment by drawtheliner** [comment]
> On a side note, I don’t know how important it is for you that your data never leaves your local network, but I think this is not guaranteed with syncthing and anytype either, both likely likely will use Internet connected machines to do syncs in certain scenarios. I’m sure this is all encrypted, so it should be safe, though.

It's very important for me. As far as I know they can both be used local only.

Syncthing: https://forum.syncthing.net/t/limit-syncthing-to-only-use-local-network-review-and-suggestions-appreciated/20117/4

Anytype: https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode

Can you share links explaining why you believe my data isn't only local with these two apps I mentioned?
