### ISSUE TITLE
Emoji aliases

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#246]
I use specific emoji for specific use cases but cannot always remember their name. It would be nice if I can specifics aliases for existing emoji that I can use to find them more easily. 

These aliases can be configure in `SETTINGS`

**Comment by yorrd** [comment]
maybe instead of going through the pain of re-inventing, we could use an existing alias list?

I'm aware of this one for example: https://emojibase.dev/emojis . While additional configurability is nice, I have to admit I have never missed custom aliases in my applications if they have some kind of alias / tags available by which to discover the emojis
