### ISSUE TITLE
directive autocomplete only works for closing tags?

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#279]
it seems like the autocomplete for directive only triggers when typing the closing tag, not the opening one, which would probably more helpful. 

Ideal behavior might be to start typing `#q` and get an autocomplete for the query directive block, or at least trigger autocomplete by the time you have `<!-- #q`

recording below: 
![Jan-04-2023 13-08-46](https://user-images.githubusercontent.com/867661/210621317-69edf610-bd3c-4151-9462-575120e581f7.gif)

**Comment by tristansokol** [comment]
I wasn't aware of slash commands, so it seems like the issue could also be that closing directives are also triggering slash commands.

**Comment by zefhemel** [comment]
Yeah, I think the real issue is that slash commands maybe shouldn’t trigger inside HTML-style comments.

But I also agree that it may be useful to do auto complete when you end up typing the start part of a directive.

Personally I only ever use slash commands to create directives, so just `/query` and it expands to the open and close tag.

**Comment by zefhemel** [comment]
Will become irrelevant with #529
