### ISSUE TITLE
Plug Idea: Webhooks

### ISSUE THREAD

**Issue by nnarain** [silverbulletmd/silverbullet#333]
I don't know the full capability of silverbullet at the moment but I think a webhook plug would be useful for automation of external applications.

For example:

The creation of a task (such as #327 and #323) fires a webhook with a JSON blob of the task data. That blob makes its way to an application like https://github.com/Casvt/Noted that handles notification scheduling through the users preferred service.

Another example. The creation of an external link is detected. That webhook is used to automated the archiving of the webpage in something like https://github.com/go-shiori/shiori. I think that would work nicely with #247 

 Perhaps the better approach would be dedicated plugs for each of these things. I've been using `n8n` recently to do simple API re-mappings so that's kind of where my head is right now.

**Comment by zefhemel** [comment]
I like the idea of adding other ways to easily extend SilverBullet in new ways and web hooks make sense to add from that perspective. What is less clear to me is when a web hook should be triggered. Your example of creating tasks seems hard, because when do we consider a task added? In a task manager there’s usually a “Add” button that you push when done, but SB doesn’t have this. There’s explicit “and hereby I consider this task ready” point in time. Since pages are constantly saved (with perhaps a 1-2s lag) it’s really not clear when the webhook should be triggered. This would be more clear for events like ticking a task as completed. Any thoughts on this?

**Comment by zefhemel** [comment]
> An incoming webhook would be great too -- would allow for a scenario like starring a message in Slack turning into a task in Silverbullet.

This is also doable (technically already possible if you’d know how — but no docs on this 😉 ). However, it would require your SB instance to be accessible directly from whatever is triggering the webhook (in you Slack example: the public internet). Most of us (I would say: probably almost everybody) run SB locally or, a local network or VPN, and while there’s ways to get the outside internet to call back into SB this is usually not straight forward.

**Comment by jhofker** [comment]
> This is also doable (technically already possible if you’d know how — but no docs on this 😉 )
👀 well now I'm interested! (I can make a separate issue for this if it's useful btw...)

Like nnarain, I have n8n running and publicly accessible, it's connected to Slack and listening for events and it would have internal network access to SB, which is where my interest comes in. 

Totally understand if that scenario isn't a high priority to support since it's likely to be so rare.

**Comment by zefhemel** [comment]
I should really document this, but in a plug you can do this:

```
name: myplug
myHTTPFunction:
  path: ./http.ts:myHTTPFunction
  http:
     path: /hook
```

This would result in any HTTP get, post, options request sent to `http://yoursilverbulletinstance:3000/_/myplug/hook` (so your SB instance `/_/PLUGNAME/PATH`) and invoke myHTTPFunction on it, where that function then has to return a HTTP result. For instance:

```
export async function myHTTPFunction(req: any) {
  return { status: 200, body: "Hello world" };
}
```

Shape of the request and response objects can be found here: https://github.com/silverbulletmd/silverbullet/blob/main/plugos/hooks/endpoint.ts

Test here: https://github.com/silverbulletmd/silverbullet/blob/main/plugos/hooks/endpoint.test.ts

**Comment by jhofker** [comment]
Thank you!

**Comment by nnarain** [comment]
That's a good point on when a task webhook would fire. I'd have to think about that. I suppose I'd settle for a semi-automatic process where I could trigger an update from the command palette.
