### ISSUE TITLE
some keyboard shortcuts are not well selected

### ISSUE THREAD

**Issue by jwalzer** [silverbulletmd/silverbullet#337]
# Issue

some keyboard shortcuts are not well selected

### Description
* The Keyboard Shortcut for refreshing of queries (`Alt`+`Q`) is not a very good selection. Especcially on MacOS its very next to (`Cmd`+`Q`) which closes the browser. Especially since other hotkeys are often in combination of `Cmd` its happened quite often, that the wrong modifier is pressed while trying to refresh the query.
  
* The Keyboard Shortcut for Command Menu (`Cmd`+`/`) is hard to reach (as in “does not work) on MacOS in German Keyboard Layout as the `/` key is only created by pressing Shift modifier (`Shift`+`7`).

**Comment by zefhemel** [comment]
Open to suggestions for alternatives. The `Alt-q` is a bit legacy, from when the time that this was “Update Queries” — open to alternatives here for sure.

The `Cmd-/` I like because we also use plain `/` for slash commands, but I can see that on certain keyboards this is problematic. What we can do there is for instance also add `Cmd-.`/`Ctrl-.` as an alternative (I had that before I moved to `Cmd-/`) once upon a time. 

Thoughts?

**Comment by Gugi264** [comment]
I also don't like `Ctrl-/` as I am on a german keyboard.
`Crtl-.` seems like a good alternative for me.
