### ISSUE TITLE
documentation, how to create a "read only" instance

### ISSUE THREAD

**Issue by jwalzer** [silverbulletmd/silverbullet#349]
Like the [Silverbullet.md] website, setting up an instance that does not allow editing but anonymous Read-Only access would be helpful for usecases.

I can see scenarios, where edit-instances are living in private environments that sync via git to externally readable instances.
I assume this would additionally need some kind of external trigger mechanism to tell an instance to pull the latest version...

**Comment by itsamemarkus** [comment]
This would be cool. I noticed you can achieve read only by just changing permissions to the markdown files so that the user running silverbullet cannot write to those files. (but read)

![image](https://user-images.githubusercontent.com/34944988/215257133-7c9ecdd6-98ac-4a62-ba14-e037ee059b34.png)

On top of that it would be cool to disable the editing functionality (no cursor) for the read only instance. I'm really considering using silverbullet as a blog. It's just so frictionless to add new content.

**Comment by itsamemarkus** [comment]
I think this issue can be closed to continue the discussion it at #161
