### ISSUE TITLE
Quick note filename uses Windows reserved character (colon)

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#364]
The quick note file name `📥 2023-01-31 16:00:43.md` contains a `:` which is a [reserved](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) Windows character which leads to errors. Noticed this when I wanted to git clone my library to a Windows machine and couldn't.

https://user-images.githubusercontent.com/34944988/216777594-9bdbd15a-b0a9-49fd-9c98-b66e50a51685.mp4

**Comment by zefhemel** [comment]
Hmm, right... For sure we can change this something without colons, but this leaves the question: what should we do when somebody creates a page with a colon (or other non acceptable character), disallow it? Translate it to something else? Suggestions?

**Comment by itsamemarkus** [comment]
I don't prefer the don't allow way, maybe URL encode all potentially dangerous characters? Some markdown files wouldn't look that great:

 `Test: Testing.md` becomes  `Test%3A Testing.md` but that might be rare enough so that it doesn't affect the readability of raw markdown filenames too much overall.

| char | URL encode |
|----------|----------|
| `<` | `%3C` |
| `>` | `%3E` |
| `:` | `%3A` |
| `"` | `%22` |
| `/` | `%2F` |
| `\` | `%5C` |
| `\|` | `%7C` |
| `?` | `%3F` |
| `*` | `%2A` |

**Comment by zefhemel** [comment]
It's not just about the URL though. What should a page name with a colon be named on disk on windows?

**Comment by itsamemarkus** [comment]
I was thinking about the same as URL. It doesn't look nice but maybe those characters aren't used that much anyways.

Or we would come up with an alternative sequence starting with a character that is then not allowed by Silverbullet then.

Example for files with URL encoding scheme:
```
.
├── Linux
│   ├── Debian.md
│   ├── Suse.md
│   └── Ubuntu.md
├── Page%3A Testing.md
├── SilverBullet.md
├── SomeNormalFile.md
└── Test%3A Folder
    ├── knowledge.md
    └── moreknowledge.md
```

Obsidian has a pretty strict approach:

![image](https://user-images.githubusercontent.com/34944988/218305247-68b849de-cf4c-4a20-b4e4-fe6d640d9afb.png)

**Comment by zefhemel** [comment]
Yeah, rejecting such characters probably is the cleanest solution. Question is what to do with files that already have these characters in their name.

**Comment by jwalzer** [comment]
So, as a non-windows-user, I would insist, that on-disk I want to drop wiles with any allowed filename into the space directory. For limitations I would expect anything that works with **git** to also work with SB.
If git can't checkout filenames with colons in it on a different plattform, is this a failure of git?

I choose git as an example, because I have hopes to get git running as a backing store for syncing between different instances.

**Comment by ndtoan96** [comment]
It's hard to think of a best way for the naming, but can we at least change quick note template naming in the mean time so it works on Windows. Because it is one of the core features, we can't just leave it broken like that.

**Comment by Maarrk** [comment]
How about we add a function `{{dateTimeCompact}}` which would return string like `20240722T144025` for today? This is defined as "basic format" in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

I wouldn't change the default to that, but would suggest putting this as a suggestion in Library/Core/New Page/Quick Note:

```yaml
hooks.newPage:
  suggestedName: "Inbox/{{today}} {{time}}"
  # When hosting on Windows, use instead:
  # suggestedName: "Inbox/{{dateTimeCompact}}"
```

Optionally look at a places where date is parsed and also make it recognised there.

For people who already have notes with current naming scheme and would like to pass to a new one, there could be a Plug that parses names of all relevant pages and renames them all to a given format, using SilverBullet internals so the links don't break etc.

**Comment by zefhemel** [comment]
That's one way to go, but it's a bit of a hurdle for Windows to jump over. They'd need to exclude the default Quick Note from the library and create their own version. It's doable, but I prefer a solution that just works for all. I was thinking of using underscores instead of colons, but that's also a bit ugly....

**Comment by bjeanes** [comment]
> I was thinking of using underscores instead of colons, but that's also a bit ugly....

This is what Logseq does for these kinds of characters. They don't store the files hierarchically, so they do this for `/` too. `Foo/Bar` becomes `Foo__Bar.md`

**Comment by meain** [comment]
FYI, this is also an issue on Android devices. You cannot use `:` on android.

**Comment by meain** [comment]
@zefhemel Looks like we went from `{{date}} {{time}}` to `{{date}}/{{time}}` (slash between date and time) with the new version of [Quick Note template](https://github.com/silverbulletmd/silverbullet/blob/main/website/Library/Core/New%20Page/Quick%20Note.md?plain=1). Just bringing it to your attention in case this was not intentional.
