### ISSUE TITLE
Errratic scrolling behaviour for longer pages with images

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#368]
I often have multiple screenshots in one page and noticed that the scrolling is weird. It might have to do something with lazy loading the content.

This doesn't happen with only text.

## Video Example

Chrome 109.0.5414.120 and Firefox 109.0.1 on Windows 11 (22H2 - Build 22621.1194)

https://user-images.githubusercontent.com/34944988/218333065-b230cd95-e9d0-447b-80e4-55c1fc8c19a3.mp4

**Comment by zefhemel** [comment]
It likely does, let me look into the options here.

**Comment by zefhemel** [comment]
Two options:

1. Somehow force pre-rendering of the entire page, even though CM has been built not have to do this for performance reasons
2. Have a way of knowing the height of an image upfront, so that it's taken into account in the rendering (I think there's an API for this). For this, likely we'd have to somehow encode at least the image height in the markdown using some notation.

**Comment by zefhemel** [comment]
Ok this took a while, but I think this should now be fixed. I opted for caching the heights of images in the data store, it's possible that during a first load this behavior still happened, but everything after that should be good.
