### ISSUE TITLE
Possible hang at startup

### ISSUE THREAD

**Issue by ajbouh** [silverbulletmd/silverbullet#372]
I've been experimenting with running SilverBullet within a Docker container on a network-backed FUSE filesystem and encountering some strange behavior. In one scenario, SilverBullet seems to hang at startup.

When I run the same container on a normal local filesystem it finish starting without an issue.

Here's what I see in the output when it hangs:

```
Going to start SilverBullet binding to 0.0.0.0:8080
Serving pages from /spaces/data/tree
Going to load 9 plugs...
Loading sync
Loading plugmd
Loading core
Loading markdown
Loading share
Loading emoji
Loading directive
Loading tasks
Loading collab
Now reindexing space...
Now starting sandbox for core
[Sandbox log] Clearing page index...
Now starting sandbox for sync
```

What is the "sandbox for sync"? Does that provide a clue as to what might be going wrong or what I can do to investigate further?

**Comment by zefhemel** [comment]
When you say "hangs" do you mean the page does not load at all when you go to localhost:8080?

The sync plug only really does anything when you have [Sync](https://silverbullet.md/Sync) enabled in your project (but it does kick in every minute, even it does nothing). My point is: this is not the culprit.

I'm suspecting SQLite may be the issue here. There is a `--db` flag you can pass to configure the path of the sqlite database to use. Could you try passing it a (relative) path outside of your FUSE filesystem (`--db ../../../someotherplace.db`) and see if that changes anything?

**Comment by ajbouh** [comment]
By "hang" I mean startup never completes and the port is never opened for listening.

I will try the alternative path and get back to you. Is there extra logging I can enable?

**Comment by zefhemel** [comment]
Since this issue is stale I'll close it. Please reopen if it's still an issue.
