### ISSUE TITLE
Renaming page with underscores creates a second file

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#374]
_probably an edge case that is rarely encountered_

## current behavior

- Adding a new site `Silver Bullet`  generates the file `'Silver Bullet.md'`. 
  -  page shows as  `Silver Bullet` in the browser
- Adding a new site `Silver_Bullet` generates the file` 'Silver Bullet.md'` (same filename as before)
  -  page shows as  `Silver Bullet` in the browser (same as before)

## renaming `Silver Bullet` to `Silver_Bullet`

renaming the existing page `Silver Bullet` to `Silver_Bullet` in web UI generates an additional file so you end up with

`'Silver Bullet.md'` and `Silver_Bullet.md` on the filesystem.

The first page isn't accessible anymore then.

## reproduce

in web UI:
- Add a new site `Silver Bullet`
- type something in there
- Rename page to `Silver_Bullet`
- type something in there too
- You can't access the first page you created anymore

files look like this then

![image](https://user-images.githubusercontent.com/34944988/221665978-77a384b7-a0fe-43a2-b876-63444fc5b6b4.png)

**Comment by jwalzer** [comment]
yes, there is already a issue open, I believe, because `_` is substituded by ` ` mostly everywhere. I have run myself already into that multiple times. Creating pages with underscores and spaces externally, outside of SB gives quite some headaches ...
But I assume, we can't simply change that, without breaking existing SB installations

**Comment by itsamemarkus** [comment]
@jwalzer thank you. Duplicate of #152 
Will close this then.
