### ISSUE TITLE
Keyboard shortcuts while cursor is in the title don't work

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#423]
If you hit `CTRL+K` or `CTRL+S` etc while editing the title, the browsers native function takes over, and you lose the focus. I think those shortcuts should always work, wherever you are on the page.

**Comment by firasdib** [comment]
To expand on this, the key listener should listen on the entire page, so focus doesn't matter

**Comment by zefhemel** [comment]
Pointers: https://github.com/silverbulletmd/silverbullet/blob/main/web/components/mini_editor.tsx#L173

https://github.com/silverbulletmd/silverbullet/blob/main/web/editor_state.ts#L71

**Comment by fflorent** [comment]
The corresponding permalinks:
https://github.com/silverbulletmd/silverbullet/blob/e7eba107c6f86b9351ffc2ea998121bc9bdda7b3/web/components/mini_editor.tsx#L171
https://github.com/silverbulletmd/silverbullet/blob/e7eba107c6f86b9351ffc2ea998121bc9bdda7b3/web/editor_state.ts#L272

**Comment by fflorent** [comment]
I see that the keybindings are already injected in the mini-editor:
https://github.com/silverbulletmd/silverbullet/blob/e7eba107c6f86b9351ffc2ea998121bc9bdda7b3/web/components/mini_editor.tsx#L198

Also tested and it seems that I can trigger shortcuts like `<Ctrl-K>` or `<Ctrl-S>` in the title.

For me, the issue is already fixed thanks to this commit: https://github.com/silverbulletmd/silverbullet/commit/a9ce68860e61a48d0df090b27b3f5392f172f595

:)
