### ISSUE TITLE
Tini warning on docker start

### ISSUE THREAD

**Issue by pgr0ss** [silverbulletmd/silverbullet#477]
When I run the docker image, I get a Tini warning on start:

```
% docker run -it -p 3000:3000 zefhemel/silverbullet

[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
```

It looks like the entrypoint is tini, so I'm not sure the issue: https://github.com/silverbulletmd/silverbullet/blob/5fef8a870f679d95bf7f72b789d7243c0660bcfa/Dockerfile#L50

**Comment by ixdy** [comment]
I think part of the issue might be that the entrypoint is configured in the shell form, rather than the exec form.

Per the Docker [reference documentation](https://docs.docker.com/engine/reference/builder/#entrypoint), this subtle difference results in the entrypoint being started as a subcommand of `/bin/sh -c`, which does not pass signals, largely defeating the point of using Tini at all.

Additionally, using the shell form of `ENTRYPOINT` means that any additional command line arguments are _not_ passed along - so this example from the `Dockerfile` doesn't actually work: https://github.com/silverbulletmd/silverbullet/blob/5fef8a870f679d95bf7f72b789d7243c0660bcfa/Dockerfile#L49

Curiously, prior to #403, the Dockerfile _did_ use the exec form of `ENTRYPOINT`. @zefhemel was this an intentional change?

**Comment by zefhemel** [comment]
It was intentional, but I forgot the reason. I think we can roll that back. Happy to take a quick PR otherwise I'll look at it next week probably.

**Comment by pgr0ss** [comment]
I'm not sure if this is the reason or why, but the docker image doesn't run for me anymore:

```
% docker run -it zefhemel/silverbullet:latest 
% echo $?
139
```
But the old version runs:
```
% docker run -it zefhemel/silverbullet:0.3.4
[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
Going to start SilverBullet binding to 0.0.0.0:3000
SilverBullet is now running: http://localhost:3000
```

**Comment by zefhemel** [comment]
Did you pull the latest? `docker pull zefhemel/silverbullet`? For me it runs fine?

```shell
$ docker run -it zefhemel/silverbullet:latest
Going to start SilverBullet binding to 0.0.0.0:3000
SilverBullet is now running: http://localhost:3000
```

**Comment by pgr0ss** [comment]
Yes, and I noticed that even 0.3.5 fails for me. Debugging further, it looks like the deno command segfaults for me on 0.3.5 and later:
```
% docker run -it --entrypoint bash zefhemel/silverbullet:0.3.5
silverbullet@1d9ef560e0ad:/$ deno run -A /silverbullet.js -L0.0.0.0 /space
Segmentation fault
```

I'm on an intel mac, docker desktop version 24.0.2.

**Comment by pgr0ss** [comment]
Locally for me, downgrading the deno base image fixes the problem:

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM lukechannings/deno:v1.35.2
+FROM lukechannings/deno:v1.34.3
```
So it seems like something in the deno base image is the culprit.

**Comment by zefhemel** [comment]
That's really odd. I'm running on an Mac M2 myself so I think I'm pulling the arm64 image, but on my home server (intel linux) I'm running the intel one for sure, so how would this be different between mac docker on intel vs linux docker on intel...

**Comment by pgr0ss** [comment]
I'm not sure. This is the only thing I could find that sounded similar: https://github.com/denoland/deno/issues/19926
