### ISSUE TITLE
Materialized task queries are not automatically updated once task is marked as done

### ISSUE THREAD

**Issue by radosny** [silverbulletmd/silverbullet#52]
Once you'll update the task status to "done", then the materialized query is not updated. As a result, if you have a list of unfinished tasks mentioned task (which is already done) will be still there.

It would be nice if materialized queries (query task specifically) will be updated on every change of the task [ ] -> [x]

**Comment by zefhemel** [comment]
This is possible to do, but would you really like this to happen instantly? Sometimes I accidentally check a box for instance. And if it's instant it may be confusing because "where did my task go?"

Task managers often have delayed responses for this reason I think. What's worth considering is giving it a few second delay perhaps. We would have think how to model this in general, because queries are statically calculated on demand, not "event streams" at this point. We can explicitly schedule a timed query refresh when ticking a todo box I suppose, but...

Until then: what I've learned to do after completing a bunch of tasks is just hit `Alt-q` every once in a while.

**Comment by zefhemel** [comment]
I'll close this, since I see it as desired behavior. Also with the new live preview behavior, tasks are very clearly marked as done now.
