### ISSUE TITLE
Markdown alternative: org mode

### ISSUE THREAD

**Issue by Melkor333** [silverbulletmd/silverbullet#536]
Maybe a bit of a stupid request. And not something I currently plan on doing, mostly wondering if even possible:

Given that [org mode syntax](https://orgmode.org/worg/org-syntax.html) supports tags, options, inline code results, planning, etc. it would "natively" support a lot of things which are currently covered in a "nonstandard" way.

Do you think it is *technically* possible to implement org syntax as an alternative to Markdown without having to do a complete rewrite?
Or is there too much hardcoding / codespecifics that expect a markdown syntax?
Ignoring that many plugins like silverbullet-ghost depend on the syntax and wouldn't work anyway.

**Comment by zefhemel** [comment]
Let me start with saying: everything is possible, the sky is the limit :) That said, this would take significant effort. First it would require a codemirror syntax for org mode. I just googled a bit and it looks like there's nothing that is actively maintained. Second probably a lot would simply have to be reimplemented, because it is indeed specific to markdown syntax. 

Given that this is mostly a one developer spare time project I don't think this is realistic unless I'd go all in on org mode and do that instead, but I don't think that's going to happen and we'd lose a lot the audience with that.

**Comment by Melkor333** [comment]
No qorriew, exactly what I was expecting.

I'm just a bit torn between the org docs I still have from emacs and the nice web UI this project gives (plus awesome mobile accessibility!!). And while trying to convert my org notes to Markdown I realized that a lot of information is lost.

I did find an [org parser](https://github.com/200ok-ch/org-parser) - not sure how hard it would be to use this as a base for a codemirror highlighting. But since you say that a lot depends on Markdown I won't dig any deeper for now. I understand that this would have to be implemented by myself!

And also thanks a lot for making your project open source, allowing everyone to use it, making such great docs and keep making it better!!
