### ISSUE TITLE
task template showing up as a task when querying tasks

### ISSUE THREAD

**Issue by thinkbig1979** [silverbulletmd/silverbullet#550]
So I've fresh installed Silverbullet today and am getting to know the app now.
I created a page called template/task, and inserted the below task template into that page. 
`* {{state}}  {{ref}} {{name}}`

Then I created a page called `tasks` with tasks and queried those tasks from another page called `home`, with the following query:
query task render [[template/task]]

The query list on the `home` page actually lists the task template as a task.
So this is showing in the queried task list:
* {{state}} task@2 {{ref}} {{name}} 

Is there an elegant way to ignore template pages when using 'global' queries without having to exclude template pages manually in the query itself?

**Comment by zefhemel** [comment]
Good question, since template pages are not special in any way I don't have a very elegant solution for you. What you can do is add `where page !=~ /^template\//`clause to your query, which should filter out all tasks on pages that start with `template/`.

Btw, it looks like you're trying to build up a task list here, you may want to use this: https://silverbullet.md/template/task either by copy and pasting that into your space, or referencing it directly: `[[!silverbullet.md/template/task]]`

**Comment by zefhemel** [comment]
There’s different ways to approach this. What I found is that querying all tasks unfiltered is hardly ever useful. Instead I either tag them with a hashtag, e.g. `#next` and query that, or filter based on other things like page references that appear inside of the task name.

But indeed, the idea to have a setting to exclude certain paths from being indexed actually does make sense also 🤔

**Comment by thinkbig1979** [comment]
Nice :-)

**Comment by zefhemel** [comment]
Ok, so what I added in 0.5.4 is that all pages you tag with `#template` will no longer be indexed. I think this would solve your issue, right? You can put this in the template's frontmatter or just put a `#template` at the very beginning of your page. Example: https://silverbullet.md/template/task

**Comment by thinkbig1979** [comment]
Yep, that'll do it. Thanks!
