### ISSUE TITLE
Assign emoji to specific tags, or at a per-page basis

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#560]
These emoji would then appear:
* In the page title (top bar)
* In page links

e.g. let’s say we assign 📕 to the `#book` tag. A page “Harry Potter” tagged with `#book` would then appear as e.g. “📕 Harry Potter”

How to configure?

* Perhaps a `icon` key in front matter for per-page configuration
* Per tag… TBD

**Comment by v411e** [comment]
My thoughts on that:

**tag-wise**
\+ does not clutter the front matter that much
\+ scales great
\- might overload the whole tag thing. In the end someone might need to use a `book-icon` tag, because of exceptions where a page tagged with `book` should become no icon at all
\- what if a page has multiple tags with icons? Which icon will be chosen? Precedence?

**`icon: ''` in frontmatter**
\+ No ambiguity with precedence of multiple icons
\- Does not scale well. Has to be defined on every single page. Imagine you have a collection of 50 pages where you want an icon. You would have to update every single file.

**rules in `SETTINGS.md`**
\+ best scaling
\+ does not clutter front matter or tags
\- what if a page has multiple rules that apply? Which icon will be chosen? Precedence?
\- complex

I think a combination might be best.

**Comment by paletochen** [comment]
I love this feature request.

@v411e I believe all options require the same amount of work:

- **tag-wise**. If you have 50 pages, you need to add a tag to each one of them in frontmatter (you can automatize this with templates for future pages of that type)
- **icon**: Same, you need an icon in every page
- **SETTINGS.md** I am not sure this option is any different from tag-wise as in the latter, you also need to define somewhere which icon will be assigned to each tag

If I could choose, I'd go for using tags and define a key:value list in SETTINGS.md with:
- tag:icon

And then in every page we would only need to add the desired tag.

I find this option cleaner. Using the same example of 50 pages, this option would mean having 50 pages with tags in their frontmatter, instead of 50 icons.
Text is simpler to handle within the terminal, for example.
Icons would only be present in SETTINGS.md

Hope this makes sense

**Comment by v411e** [comment]
@paletochen In regard to the defining rules in `SETTINGS.md`: I was thinking about some kind of regex, but yeah I agree, tags are probably the best solution :)

**Comment by zefhemel** [comment]
If we want to go really advance, we may support full blown query selectors (think: `where tags = “something” and …`) but that may be overkill. I think I’ll go with tag-based mappings first.

Perhaps something like this?

```yaml
decorations:
   - tag: book
      prefix: “📕”
```

This would allow for other type of selectors in the future.

**Comment by paletochen** [comment]
> Perhaps something like this?
> 
> ```yaml
> decorations:
> - tag: book
>   prefix: “📕”
> ```
> 
> This would allow for other type of selectors in the future and other type of decorations, like color, or background color. Now the question is if this should be named “decorations” or “linkDecorations” or something, and if it should apply just to the links or also appear in the page’s title?
> 
> Since this would be an ordered list, we can just say that “the first match wins”

I think the implementation proposed is simple and efficient. I let you decide on the name :)
As for the outcome, I'd love to see it apply on the page's title.

A graphical example of what I mean:

A setup like this:

```
decorations:
- tag: person
   prefix: "🧑 "
```

would allow me to see a page like this:

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/ba605399-e7e4-4d12-8c44-61246cc2b057)

it would appear in queries like this:
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/f0f7f64c-f791-41a0-8d6d-d272c22b69b0)

or like this:
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/2a47499d-3261-45f5-bd04-fb8d7d4e033d)


while in the url, the true link would be `https://mysilverbullet.com/Zef`
and the file in the filesytem would look like this:

```zsh
>ls -l
rw-r--r-- user user 521 B  Thu Nov 15 18:28:43 2023 Zef.md
```

**Comment by zefhemel** [comment]
Yes that looks good. And I find your example strangely appealing 😛
