### ISSUE TITLE
Bug: Symlinked folder content is not indexed on MacOS

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#740]
When creating a symlink pointing to a folder containing `.md` files, that is located outside of my space directory, SB does not discover these files. Not even when running the reindex command manually.

**Comment by zefhemel** [comment]
I'll check this, to clarify are you running this with docker or directly with Deno?

**Comment by gorootde** [comment]
Plain deno

**Comment by gorootde** [comment]
I investigated a little bit and found the root cause:

`disk_space_primitives.ts#fetchFileList()` uses `walk()` to build a list of all files in the space. A symlinked directory is resolved to the target path of the symlink. That leads to the `fullPath` not being inside the space directory.

In the end fixing this would lead to changing the `safePath` function to accept target paths of all symlinks in the space directory as well. Also almost all SB code assumes that all files are located inside the space path.

**Comment by zefhemel** [comment]
Yeah I'm not 100% sure how to solve this. I think the safePath contraints we can drop, I think it's ok to be "unsafe" but it seems `walk` is always resolving symlinks to full paths, which is probably not what we want. I think this would require using an alternative to `walk` that follows symlinks, but keeps path in tact so that it still looks like these files are nested under the root path.

**Comment by zefhemel** [comment]
Ok I'm always a bit scared to do this, but I just replaced the `walk` call with a custom version that walks symlinks, but preservers their paths. I tested it and for me it seems to work, can you check too? I hope this doesn't regress other features but let's hear if people scream.
