### ISSUE TITLE
Feature request: Markdown extension for superscript/subscript

### ISSUE THREAD

**Issue by KoiledLobster** [silverbulletmd/silverbullet#872]
When displaying a number with an exponent, it would be nice to be able to superscript the exponent without needing to pull in a latex renderer.

Syntax could be along the lines of `^superscript text here^` for superscript, unsure how subscript is typically exposed in markdown extensions.

**Comment by MrMugame** [comment]
@STSMHQ You are kind of hijacking the issue here lol, but he is probably using the [KaTeX plug](https://github.com/silverbulletmd/silverbullet-katex). A typst plug should definitely [be possible](https://github.com/fenjalien/obsidian-typst), but that would not be something silverbullet directly supports.

**Comment by MrMugame** [comment]
@STSMHQ Ok so I threw [something](https://github.com/MrMugame/silverbullet-typst) together real quick, which was pretty easy thanks to a cool library called [wypst](https://github.com/0xpapercut/wypst), which is a drop-in replacement for KaTeX. It's far from finished and the way it works is a little weird (It more or less crosscompiles to latex and renders it with KaTeX), so don't expect to much, but the guy working on it said he'll put more time in starting today actually so, give the guy a star.

**Comment by MrMugame** [comment]
@STSMHQ It's in the readme
