### ISSUE TITLE
Everything breaks when using markdown preview

### ISSUE THREAD

**Issue by Rokainu-Codes** [silverbulletmd/silverbullet#986]
When trying to use the markdown preview command either in my own silverbullet instance or on silverbullet.md the title shifts, no markdown is shown and the following error pops up in the console:
![image](https://github.com/user-attachments/assets/10534f7d-a0a6-469a-9056-0ad5ded80349)

Afterward the page picker and command palette do not seem to respond anymore either until reloading or deleting cookies.

**Comment by joekrill** [comment]
I think this is what is also the cause of a [similar error with the Tree View plug](https://github.com/joekrill/silverbullet-treeview/issues/21) in the latest release. I think it's being caused by the [`useRef` call on the first line of the `Panel` component](https://github.com/silverbulletmd/silverbullet/blob/36deb6a0a1f8637a5c3de6e179d514ba2724da0c/web/components/panel.tsx#L13). So effectively anything that calls `showPanel` is likely affected. 

I've been trying to narrow down the underlying cause but haven't found anything _concrete_ yet, but I think it is related to upgrading the Preact version: It was upgraded [dependency upgrades](https://github.com/silverbulletmd/silverbullet/commit/230bb2ab8bb3b101e17b0de53851fa1c58f0535e) in the latest release, an if I downgrade Preact back to v10.11.1 things seem to work again.

There's [this issue](https://github.com/preactjs/preact/issues/4035) that might be a clue? So perhaps esbuild is causing a problem here?

**Comment by joekrill** [comment]
Ah just figured it out: the [import statement in `panel.tsx`](https://github.com/silverbulletmd/silverbullet/blob/36deb6a0a1f8637a5c3de6e179d514ba2724da0c/web/components/panel.tsx#L1) is importing from Preact v0.11.1 causing multiple copies of preact to be used. Easy fix - I'll put up a PR for it in a minute.

**Comment by zefhemel** [comment]
Ok. I'll probably another bug fix release soon, but it should be live on the edge builds soon.
